### ISSUE TITLE
pass opsetid object instead of just opset in frontend

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#102]
About `tensorflow_graph_to_onnx_model`,
current `opset` is an attr passed to method and use `helper.make_opsetid('', opset)` to create opsetid.
I think a better idea is let user pass opsetid object directly.

**Comment by tjingrant** [comment]
How about supporting both? With a different keyword arg like opsetid_obj?

**Comment by fumihwh** [comment]
Or let opset accept both int and obj?

**Comment by tjingrant** [comment]
That works for me as well. 
Also, what's the benefit of allowing users to pass in the opsetid object? Is it the ability to specify custom domain?

**Comment by fumihwh** [comment]
Yes. Also `ai.onnx.ml` domain which is officially supported, if I remember correctly.

**Comment by fumihwh** [comment]
Should we provide frontend support by domain? or just by version as current?
 
For example, {'': 6, 'ai.onnx.ml': 1}.
We put them into model by `model.opset_import.extend(opset_imports)` to point out which custom operator sets imported by the model.
The problem is we have frontend_vx now, is it cool to keep them (put `ai.onnx.ml:1` into frontend_v1) or should add domain compatibility with frontend_{domain}_vx?
I think it makes things complex (gen_doc should be updated also) but a little more sensible.

What do you think?

**Comment by tjingrant** [comment]
Ultimately yes. But frankly I do not yet quite understand how this opset_import is supposed to work. Do you see any documentations about this topic?

I'm actually quite confused; say if I import opset_ver=6, does it mean we import only 6? Or use 6 as the first choice, then go to 5, 4, 3, 2, 1 if a later versioned op is not available. Because if we only import opset_ver=6, technically there aren't many ops in that opset.

Do you know where to learn more about how opset_ver is supposed to work?

**Comment by fumihwh** [comment]
Mainly from `Versioning.md`. Key point is: the opset is `since_version`.
For example, Reshape has [1, 5], you can find it from `opset_version.py`. It means since opset=1, we should use handle_reshape in frontend_v1 until next since version if has. So in this case, under opset=4, we will use handler_reshape in frontend_v1 and from opset=5, we should switch to frontend_v5.

**Comment by tjingrant** [comment]
Thanks the link really helps. 
I think we need to consider several things.
1. We need to be careful about what API changes we introduce because we shouldn't break API backward compatibility.
2. I'm not very excited about exposing any ONNX helper functions to the user (that'd be an extra thing that users need to learn or an extra place users need to check for documentation).

That being said, we can summarize that these are useful interfaces to specify opset information in the model:
1. No information is provided (use max opset version, but this is kinda broken now).
2. An integer opser version (currently implemented).
3. An object to the effect of: {'': 6, 'ai.onnx.ml': 1} (your proposed interface).

So 2 is good, 1 and 3 need more work..

**Comment by fumihwh** [comment]
As I said in pr, I am not sure about if onnx supports multiple domain.
From https://github.com/onnx/onnx/blob/master/docs/IR.md#model-metadata,
model metadata has domain: A namespace for the model, following the style of package names, that is, reverse DNS domain name, as 'ai.onnx.ml' (as my understanding).
And domain's type is string, not list.
So maybe I need to open an issue to ask.

**Comment by fumihwh** [comment]
As we don't know which custom domain tf operator belongs to,
maybe frontend_vx contains all domains' ops' handlers where their opset_version is x is a good idea.
e.g. frontend_v1 contains all "" domain ops' handlers whose opset_version is 1 also all "ai.onnx.ml" domain ops' handlers whose opset_version is 1 too.
Another way is creating frontend_ai.onnx.ml_v1 to hold handlers. We should make a rule that one op's has only one handler in all frontend files. e.g. handler_op_name should not both exist in frontend_ai.onnx.ml_v1 and frontend_v1.
And do more at doc and opset generation.

**Comment by tjingrant** [comment]
Yes I agree keeping them all under `frontend_vx` is a good idea. But we can distinguish the namespace by having different classes containing those handlers right? 

> one op's has only one handler in all frontend files

I think allowing duplicate handlers is the core advantage of having multiple namespaces right?  So I don't think we can restrict that.

**Comment by fumihwh** [comment]
How do we deal with case that duplicate handlers exist in multiple namespaces?
For example, operator `Add`, both `ai.onnx`('') and `com.custom` has `handle_add`, and opset_imports={'': 6, 'com.custom': 1}.
We have no idea about which handler should use, right?

**Comment by tjingrant** [comment]
To deal with duplicate handlers we need consistent rules about order of precedence of namepsaces. This itself is not difficult but we need something concrete to be written in the spec.

**Comment by fumihwh** [comment]
If opset_imports keep order, we can use that.

**Comment by fumihwh** [comment]
#104
