### ISSUE TITLE
BackendIsNotSupposedToImplementIt: LayerNormalization is not implemented

### ISSUE THREAD

**Issue by nguyencse** [onnx/onnx-tensorflow#1059]
**Describe the bug**

I face this issue when converting onnx model to tensorflow model. Please help. Thank you for your all recommendations.

**To Reproduce**

tf_model_path = "tf_model"
tf_rep.export_graph(tf_model_path)

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.10
 - ONNX version: 1.14.0
 - ONNX-TF version: 1.10.0
 - Tensorflow version: 2.14.0-dev20230511

**Comment by PINTO0309** [comment]
If you share the ONNX file with me, I'll give it a try. Since onnx-tensorflow has stopped development, I am building my own tool for equivalent or better conversion performance.

Note that I recommend downgrading onnx to v1.13.1 before generating onnx files.

https://github.com/PINTO0309/onnx2tf
- install
  ```
  pip install onnx2tf
  ```
- convert
  ```
  onnx2tf -i xxxx.onnx -osd
  ```
  or
  ```python
  import onnx2tf
  onnx2tf.convert(
    input_onnx_file_path='xxxx.onnx'
  )
  ```

**Comment by nguyencse** [comment]
Thanks for your recommendation @PINTO0309

**Comment by dalyulbam** [comment]
Thanks LOL I hope someday I would rather build my own package for this ridiculous conversion too
