### ISSUE TITLE
About the 'axis' transformation

### ISSUE THREAD

**Issue by kitstar** [onnx/onnx-tensorflow#13]
Hi guys,

I have a question about the axis transformation. In ONNX, the main dataflow is "channel_first", but in support_cuda = false case, tensorflow main dataflow is "channel_last", which means the 'axis' in 'Argmax', 'Argmin', 'Concat' ...  needs to be transformed, like "1" --> "3". But I can't find related transformation in code. Do I miss anything?

And the transformation is not needed in NLP network. How to detect if the axis transformation is needed in CNN & RNN mixed network?

Thanks.

BR,
Kit

**Comment by tjingrant** [comment]
Hi, if I remember correctly, we follow the "channel_first", or in other words, `NCHW` data format throughout. Whenever a data format transformation has to be done because a GPU is not available, we transpose it inside a node and hide this transposition from the user. Thus the tensors coming in and out of a ONNX node always appear to be in `NCHW` format from users' prospective even when the computation has to be done with `NHWC` format. This is inefficient but may provide logical conciseness for now until better solution can be proposed (I suspect changes have to be made in the ONNX specification in order to fully resolve this issue efficiently).

So axis transformation is never needed if you use our backend because you can always assume that we use `NCHW` format.

**Comment by tjingrant** [comment]
To illustrate this in context, here's the code we use inside pooling. Pooling is done in `NHWC` format on CPU. Here's the code we use to perform pooling in `NHWC` format. Notice that the input has `NCHW` format:
```
      x = tf.transpose(x, perm=[0, 2, 3, 1])
      pooled = pool_func(x, [1] + kernel_shape + [1], [1] + strides + [1], pad,
                         data_format=data_format)
      pooled = tf.transpose(pooled, perm=[0, 3, 1, 2])
```
Notice that two transpositions are present before and after pooling (that are the inverse of each other). Thus the data coming in and out of the ONNX Pooling Op are always in `NCHW` format regardless of whether a GPU is available.

**Comment by kitstar** [comment]
Hi Tian,

Got it. Tried same way. Seems we can try to remove unnecessary transpose between pooling conv and so on.

Thanks.
Kit

**Comment by fmassa** [comment]
Note that native NCHW format is not widely supported in TensorFlow, so I believe we need those transposed if we want the code to run on the CPU.  But a flag could be included that sets to use NCHW operations if enabled.

**Comment by tjingrant** [comment]
@fmassa, this is indeed a tricky problem. Would you be interested in creating this "data format" flag?

Also @kitstar, I believe when XLA is enabled (not sure about the general case), unnecessary transposition (consecutive transpositions that are inverse of each other) is automatically eliminated through transposition folding.
