### ISSUE TITLE
Fix frontend API inconsistency

### ISSUE THREAD

**Issue by philferriere** [onnx/onnx-tensorflow#157]
Currently, `convert_graph()` (aka, `TensorflowFrontendBase.tensorflow_graph_to_onnx_graph()`) and `TensorflowFrontendBase.tensorflow_graph_to_onnx_model()` params are not consistent. In one case, the `output` param is a string (output name) and, in the other, it's a NodeDef.

Making the frontend API consistent would allow me to go from the cumbersome:

```python
import tensorflow as tf
from tensorflow.contrib.slim.nets import vgg

from onnx_tf.frontend import convert_graph

def get_node_by_name(nodes, name):
    for node in nodes:
        if node.name == name:
            return node
    raise ValueError("Node {} is not found in the graph provided".format(name))

# Convert TF slim VGG 16 to ONNX
with tf.Session() as sess:
    # Setup input placeholder
    batch_size = 1
    height, width = vgg.vgg_16.default_image_size, vgg.vgg_16.default_image_size
    inputs = tf.placeholder(tf.float32, shape=(batch_size, height, width, 3))

    # Build model
    predictions, model = vgg.vgg_16(inputs)

    # Run the initializer
    sess.run(tf.global_variables_initializer())

    # Get the graph definition and preprocess it
    tfgraphdef = tf.get_default_graph().as_graph_def(add_shapes=True)
    tfgraphdef = tf.graph_util.remove_training_nodes(tfgraphdef)
    tfgraphdef = tf.graph_util.convert_variables_to_constants(sess, tfgraphdef, [predictions.op.name])

    # Get output NodeDef
    output_node_def = get_node_by_name(tfgraphdef.node, 'vgg_16/fc8/squeezed')

    # Convert default TF graph to ONNX graph
    onnx_graph = convert_graph(tfgraphdef, output_node_def)
```

to a much cleaner:

```python
import tensorflow as tf
from tensorflow.contrib.slim.nets import vgg

from onnx_tf.frontend import convert_graph

# Convert TF slim VGG 16 to ONNX
with tf.Session() as sess:
    # Setup input placeholder
    batch_size = 1
    height, width = vgg.vgg_16.default_image_size, vgg.vgg_16.default_image_size
    inputs = tf.placeholder(tf.float32, shape=(batch_size, height, width, 3))

    # Build model
    predictions, model = vgg.vgg_16(inputs)

    # Run the initializer
    sess.run(tf.global_variables_initializer())

    # Get the graph definition and preprocess it
    tfgraphdef = tf.get_default_graph().as_graph_def(add_shapes=True)
    tfgraphdef = tf.graph_util.remove_training_nodes(tfgraphdef)
    tfgraphdef = tf.graph_util.convert_variables_to_constants(sess, tfgraphdef, [predictions.op.name])

    # Convert default TF graph to ONNX graph
    onnx_graph = convert_graph(tfgraphdef, 'vgg_16/fc8/squeezed')
```

The frontend should (and can easily do) the graph walking for me.

**Comment by tjingrant** [comment]
Hi @philferriere we clearly document our public APIs on the second line of README file (for your reference https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/doc/API.md) and `tensorflow_graph_to_onnx_graph` is not in there.

Mind you, `tensorflow_graph_to_onnx_graph` is not meant to be used by a user because it is not documented in our API documentation; it is in fact merely **a convenience function for our testing infrastructure**. And for testing infrastructure, passing over string is considerably more error-prone than passing the NodeDef. On the other hand, we expect users to use `tensorflow_graph_to_onnx_model` only and that is why we created a convenient interface for it that accepts a string to specify the output node name. 

Thus by using `tensorflow_graph_to_onnx_graph`, you are using an **internal and undocumented** function not meant for general audience AND for that reason, *it is never meant to have an interface consistent with* `tensorflow_graph_to_onnx_model`. 

Therefore here is a list of things you can do:

1. use `tensorflow_graph_to_onnx_model` instead.
2. we can discuss your use case and maybe something can be done to our codebase.

So summarize, to a reasonable extent, there is no consistency guarantee once you venture into an area uncharted by our API documentation. In such area, the capability to work seamlessly and reliably with our testing infrastructure reigns over user-friendliness.

**Comment by philferriere** [comment]
Point taken. Thank you for the detailed explanation, @tjingrant!
