### ISSUE TITLE
No module named legacy

### ISSUE THREAD

**Issue by keerthanss** [onnx/onnx-tensorflow#226]
Hi,

I ran the following instructions:
```
sudo apt-get install protobuf-compiler libprotoc-dev
pip install onnx
pip install onnx-tf
```
Thus, I installed both onnx and onnx-tf. To check, I ran test_model.py, that's available in test/backend/. However, I was faced with the error "No module named legacy", in the statement "from onnx_tf.common.legacy import legacy_onnx_pre_1_2"

Based off this [issue](https://github.com/onnx/onnx-tensorflow/issues/173), I figured I must install onnx v1.1.2 from source. So I did. I installed onnx-tf using pip again, and was faced with the same error.

The only thing that worked for me finally was installing onnx-tf from source too. 

I'm still curious as to why this error occurred. Thank you very much!

**Comment by fumihwh** [comment]
@keerthanss 
Because the source at PyPI is outdated. 
The error occurs when you are trying to run the latest test(at your local, you might be working with master branch) with old package installed.
If you want to develop onnx-tf and onnx, install from source is recommended. Otherwise, you even don't need to run test.

**Comment by keerthanss** [comment]
I see! That makes sense. Thank you so much!
