### ISSUE TITLE
With adding [1] to kernel and stride in the backend pooling handler

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#29]
Hi,
I really don't understand this lines : 

```python
pooled = pool_func(x, [1] + kernel_shape + [1], [1] + strides + [1], pad,
                                data_format=compute_format)
```

Why [1] is added in both side of kernel shape and strides ? 
I had to remove these [1] to make it working

**Comment by tjingrant** [comment]
This is because in ONNX, kernel_shape and strides are specified for spatial dimensions only. For instance, a stride of [1, 1] means stride one, one in the H, W dimension. We have to tell tensorflow how to stride in the N, C dimension, thus the two [1]'s before and after. Documentation here: https://www.tensorflow.org/api_docs/python/tf/nn/max_pool.

**Comment by LucasMahieu** [comment]
From where you get this information ?
It is sais in ops doc that stride/kernel is "list of ints" one for each axes.


I think it is really unclear ...

**Comment by tjingrant** [comment]
Hi, I agree it is unclear. When developing the backend, we have to do a lot of guess work and verify it against the models here: https://github.com/onnx/models.
