### ISSUE TITLE
Where is onnx-tf?

### ISSUE THREAD

**Issue by charlesrwest** [onnx/onnx-tensorflow#302]
I'm terribly sorry, this seems like a really stupid question but...

Where is onnx-tf?
I used pip to install and it didn't show up as a command.  I manually installed from the latest stable and it didn't show up and file searches of the project don't show it.

If I may ask, how do I get the basic convert command to work?  What am I missing?

**Comment by fumihwh** [comment]
@charlesrwest 
Sorry for that. We didn't update PyPI yet.
Please install from source at present.
`pip install .`

**Comment by charlesrwest** [comment]
Thank you for the help.  I just ran that command but it still isn't showing up.

Also, running the following doesn't show that file anywhere in my system:
find / -name "*onnx-tf*" 2>/dev/null

**Comment by tjingrant** [comment]
@charlesrwest , as @fumihwh pointed out, what you need is development installation since this feature is very new.

The complete documentation is here: https://github.com/onnx/onnx-tensorflow#installation . You can double-check your steps.

To check whether you have the right version of onnx-tf with the command line functionality, check your setup.py to see whether the console script installation is specified, c.f. the setup.py from master branch: https://github.com/onnx/onnx-tensorflow/blob/bd3736d7ffedad9dfdf7aa5e967d3d6058042f0b/setup.py#L26 .

On the other hand, this feature will be made available in about 1 week on PyPI. We upload to PyPI regularly.

**Comment by charlesrwest** [comment]
Thank you both for your help.  Everything went as expected once I changed to the latest (rather than the most recent stable).

My apologies for the trouble.  I had not realized the command line tool was a new feature.

Thanks again,
Charlie
