### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: No Schema registered for Compress with domain_version of 4

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#321]
**Describe the bug**

`onnx.onnx_cpp2py_export.checker.ValidationError: No Schema registered for Compress with domain_version of 4`

**To Reproduce**

CI for released onnx fails.

**Comment by tjingrant** [comment]
This really feels like the fault of ONNX. But let me remove the test case from onnx backend test when the ONNX version is too low.

**Comment by chinhuang007** [comment]
@tjingrant Thanks for the fix. I need to pay more attention to CI. I somehow tend to ignore the CI status after a push since it always fails. Is there a way to separate the status between the latest and release in CI so it is clearer for contributors and reviewers? We seem to ignore the status for the latest anyway during approval and merge.

**Comment by tjingrant** [comment]
Fixed, closing.
