### ISSUE TITLE
An error occurred when invoking the run(self, inputs, **kwargs) API

### ISSUE THREAD

**Issue by MissDinosaur** [onnx/onnx-tensorflow#590]
**Describe the bug**
There is no bug, I just come with a problem when loading and running the onnx model by using onnx-tf API. And need your help.
My onnx model has five inputs and one output. Every input contains five elements. So after having loaded and prepared this model with generating the result " tf_rep", I invoked the run metho with tf_rep.run(feed_dict). The feed_dict is a numpy array with shape(5, 5), shown as below. 
![image](https://user-images.githubusercontent.com/48971343/78030054-18ffe900-7394-11ea-9228-7d2945c5b181.png)

![image](https://user-images.githubusercontent.com/48971343/78030666-089c3e00-7395-11ea-81b2-73c3555e7f14.png)

But an error occurred. Is the type of Inputs parameter wrong? I am not sure, but I have seen the using of tf_rep.run in your github in a similar way: [Convert a PyTorch model to Tensorflow using ONNX](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb) illustrated in the last picture. So, I think my  function call is valid. So can you help me to resolve this error,? Please, because I do not have any idea. Thank you very much.

![image](https://user-images.githubusercontent.com/48971343/78030839-4e590680-7395-11ea-8485-7d7b8398deec.png)

![image](https://user-images.githubusercontent.com/48971343/78032635-e9eb7680-7397-11ea-9688-fd71ab46cebf.png)

Here is the version information.
 - Python version: 3.7
 - ONNX version: 1.6.0
 - ONNX-TF version: 1.5.0
 - Tensorflow version: 1.15.0

**Comment by winnietsang** [comment]
@MissDinosaur the feed_dict that was created only have one tensor in it, that's why there is key error when the converter is looking for the second input "feats.2".
You can create your feed_dict as a list. 
May you modify your feed_dict like this and retry please.
feed_dict = [np.array([1,2,3,6,9], dtype=np.int64), np.array([1,3,4,5,9], dtype=np.int64), np.array([2,3,4,5,9], dtype=np.int64), np.array([1.0,1.0,1.0,1.0,1.0], np.float32), np.array([1.0,1.0,1.0,1.0,1.0], np.float32), np.array([1.0,1.0,1.0,1.0,1.0], np.float32)]

**Comment by chinhuang007** [comment]
Close because solution has been provided.
