### ISSUE TITLE
Support kernel_shape in Conv operator

### ISSUE THREAD

**Issue by terrytangyuan** [onnx/onnx-tensorflow#66]
Right now I am getting a bunch of warnings:
```
/Users/terrytangyuan/anaconda3/lib/python3.6/site-packages/onnx_tf/backend.py:677: UserWarning: Unsupported kernel_shape attribute by Tensorflow in Conv operator. The attribute will be ignored.
  UserWarning)
```
When I was trying to run a couple onnx models from onnx-models repo, e.g. `resnet50` and `vgg19`.

**Comment by tjingrant** [comment]
Yes, we don't see a case where kernel_shape is needed in TF since it can be inferred from the shape of the weight tensor. We added a warning just in case. This to me feels more like a deficiency in the ONNX spec. I think the current behavior is fair because warning usually doesn't mean that there is a problem (like an used variable in C++, this is an unused attribute).

**Comment by terrytangyuan** [comment]
Makes sense to me. Though I think we should make it less verbose. I see tens of warning messages right now.

**Comment by tjingrant** [comment]
One possibility is to turn this warning into an assertion to make sure that kernel_shape matches up with the shape of the weight tensor. I could make this happen relatively painlessly.

**Comment by terrytangyuan** [comment]
That would be great. Feel free to close this after your change. Thanks!

**Comment by tjingrant** [comment]
This has been fixed in the latest commit. Closing now.

**Comment by terrytangyuan** [comment]
Thanks!
