### ISSUE TITLE
I’d like to use NHWC format.

### ISSUE THREAD

**Issue by tancoro** [onnx/onnx-tensorflow#779]
I’d like you to create parameters that can be converted to NHWC format when converting a model whose input shape is NCHW. Like Onnx2keras.

Do you have any plans to do above?

**Comment by winnietsang** [comment]
@tancoro PR #726 should cover the feature you request above.

**Comment by winnietsang** [comment]
@tancoro I think the feature you are asking is you want to convert a model that originally accept NCHW input into a model that accept NHWC input. I'm wondering why not preprocess the NHWC input data into NCHW data format before send into the original model. And post process the return data accordingly.   
The goal of our converter is producing a working TF model, doing data format change (transpose) only when necessary based on the "device" setting  in onnx_tf.backend.prepare API

**Comment by Burton2000** [comment]
Related to this question, currently input shape stays the same as the ONNX model (NCHW) and a Transpose op is added at the start of the graph by the converter, is it possible to change the input shape so it is (NHWC) and avoid the Transpose op being added?

**Comment by chinhuang007** [comment]
We can't change the model input data format because 1. the same input (NCHW) for the source framework like Pytorch and ONNX won't work if we do so. 2. ONNX specifically states channel first as the only format for quite a few operators. The conversion has to be based on the specs.
If supporting NHWC natively in ONNX is critical, please open an issue in the ONNX core repo and maybe help implement it. Thanks.
