### ISSUE TITLE
Not able to export pb file even though the graph's inference is running correctly.

### ISSUE THREAD

**Issue by braindotai** [onnx/onnx-tensorflow#959]
I'm trying to export an onnx model to Tensorflow's pb graph file for deploying it to the edge devices. The onnx model is working just fine, even the imported model in tf graph giving the same outputs as the onnx model when inference is run for the same inputs.

So below `tf_rep.run` is working just fine, this means that the graph has been built correctly.

```python
import onnx
from onnx_tf.backend import prepare

with tf.device('CPU'):
    onnx_model = onnx.load('model.onnx')
    tf_rep = prepare(onnx_model)
    result = tf_rep.run(tf.ones([1, 3, 112, 112]))
    print(result.shape)

tf_rep.export_graph('model.pb') # giving error
```
But still, the `export_graph` command is giving an error ->
```
ValueError: Dimensions must be equal, but are 16384 and 256 for '{{node Add_41}} = Add[T=DT_FLOAT](concat_41/concat, Add_41/y)' with input shapes: [?,12,12,16384], [256].
```

I can give you my onnx file if needed, thanks for your time.

**Comment by chudegao** [comment]
@braindotai ,please provide your onnx file or similar onnx file for debug.

**Comment by braindotai** [comment]
@chudegao sure, you can download it [from here](https://drive.google.com/file/d/1FNd93nZTVBY-u-1RUapRUHwTFG-R71VH/view?usp=sharing).

**Comment by chudegao** [comment]
@braindotai I tried your onnx model with latest code(master branch), the issue is not reproduced. I think it's already fixed by PR https://github.com/onnx/onnx-tensorflow/pull/954. Please verify with the latest version. You can follow readme to install the latest version:
 uninstall previous onnx-tf: pip uninstall onnx-tf
 git clone https://github.com/onnx/onnx-tensorflow.git && cd onnx-tensorflow.
 pip install -e ..

**Comment by braindotai** [comment]
@chudegao Thanks a lot for your time. It's working just fine now!
